title: ignazweis2 blog
description: Meu blog pessoal.
author: ignazweis2

remote_theme: jekyll/minima@7957d4f

minima:
  skin: auto
  date_format: "%d-%m-%Y"
  
header_pages:
  - about.md

show_excerpts: true
  
github_username:  ignazweis2
rss: rss
